version: '3.3'
services:
  portable-typecho:
     depends_on:
       - db
     image: terwer/typecho-php:8.1.10-apache
     container_name: portable-typecho
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - "8080:80"
     restart: "no"
     volumes:
      - ./typecho:/var/www/html