version: '3.3'
services:
  db:
    image: mysql:5.7.38
    volumes:
      - ./data:/var/lib/mysql
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: typecho
      MYSQL_DATABASE: typecho
      MYSQL_USER: typecho
      MYSQL_PASSWORD: typecho

  typecho:
    depends_on:
      - db
    image: terwer/typecho-php:8.1.10-apache
    container_name: typecho
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    restart: "no"
    volumes:
      - ./typecho:/var/www/html